export interface Book {
  id: number,
  isbn: number,
  title: string,
  author: string,
  original: string,
  language: string,
  owned: boolean,
  read: boolean,
  goodreads: boolean,
  favorite: boolean,
  publisher: string,
  year: number,
  pages: number,
  genres: string[],
  summary: string,
  collection: string,
  tags: string[],
  notes: string,
  image_small: string,
  image_large: string,
  rating: number,
  //date: string,
  gr_link: string
}
