export interface Book {
  id: number,
  title: string,
  author: string,
  owned: boolean,
  read: boolean,
  favorite: boolean,
  isbn?: number,
  original?: string,
  language?: string,
  publisher?: string,
  year?: number,
  pages?: number,
  genres?: string[],
  summary?: string,
  collection?: string,
  tags?: string[],
  notes?: string,
  image_small?: string,
  image_large?: string,
  rating?: number,
  date?: string,
  gr_link?: string
}
